### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by ghost** [keras-team/autokeras#1091]
### Bug Description
Similar to this: https://github.com/keras-team/autokeras/issues/554
Training stops in AutoModel for image binary classification.
Traceback (most recent call last):

  File "<ipython-input-2-57aad6c1bf64>", line 30, in <module>
    auto_model.fit(x_train, y_train, epochs=epochs)

  File "C:\Anaconda3\envs\automl\lib\site-packages\autokeras\auto_model.py", line 258, in fit
    **kwargs)

  File "C:\Anaconda3\envs\automl\lib\site-packages\autokeras\engine\tuner.py", line 114, in search
    super().search(callbacks=new_callbacks, **fit_kwargs)

  File "C:\Anaconda3\envs\automl\lib\site-packages\kerastuner\engine\base_tuner.py", line 120, in search
    trial = self.oracle.create_trial(self.tuner_id)

  File "C:\Anaconda3\envs\automl\lib\site-packages\kerastuner\engine\oracle.py", line 149, in create_trial
    response = self._populate_space(trial_id)

  File "C:\Anaconda3\envs\automl\lib\site-packages\kerastuner\tuners\bayesian.py", line 103, in _populate_space
    self.gpr.fit(x, y)

  File "C:\Anaconda3\envs\automl\lib\site-packages\sklearn\gaussian_process\_gpr.py", line 191, in fit
    ensure_2d=True, dtype="numeric")

  File "C:\Anaconda3\envs\automl\lib\site-packages\sklearn\utils\validation.py", line 758, in check_X_y
    dtype=None)

  File "C:\Anaconda3\envs\automl\lib\site-packages\sklearn\utils\validation.py", line 578, in check_array
    allow_nan=force_all_finite == 'allow-nan')

  File "C:\Anaconda3\envs\automl\lib\site-packages\sklearn\utils\validation.py", line 60, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### Bug Reproduction
Code for reproducing the bug:
input_node = ak.ImageInput()
output_node = ImageBlock()(input_node)
output_node = ak.ClassificationHead()
auto_model = ak.AutoModel(tuner='bayesian',
                          inputs=input_node,
                          outputs=output_node,
                          max_trials=50,
                          directory=out_dir,
                          overwrite=True)
auto_model.fit(x_train, y_train, epochs=200)    

Data used by the code:
custom image dataset
x_train.shape = (998, 100, 100, 3)

### Expected Behavior
Training to continue until max_trials reached.

### Setup Details
Include the details about the versions of:
 - OS type and version: Win 10 Pro 64-bit
 - Python: 3.7.6
 - autokeras: 1.0.2
 - keras-tuner: 1.0.1
 - scikit-learn: 0.22.1
 - numpy: 1.18.1
 - pandas: 1.0.1
 - tensorflow-gpu: 2.1.0 

### Additional context
None.

**Comment by MagdyIbrahim87** [comment]
i have same problem while the input is ok (the tuner already make several trials for the same input data)

**Comment by haifeng-jin** [comment]
We have fixed this problem for the new release. Please try autokeras 1.0.3. Thanks.

**Comment by naitslup** [comment]
I still receive that Error with autokeras 1.0.3, with tuner='bayesian'.
As with @MagdyIbrahim87 it occurs after few trials

**Comment by q-55555** [comment]
I have the same issue.
It happens when the score of the trial is NaN in my case.

We need to repoen the issue.

**Comment by haifeng-jin** [comment]
I also suspect this issue still exist due to some recent user's feedback. Anyone can provide a colab notebook for reproducing the issue?

**Comment by q-55555** [comment]
@haifeng-jin, it is difficult to provide a colab because it depends on the training parameters choosen by keras-tuner and autokeras. 

All I know is that the exception "ValueError" is catched in kerastuner/tuners/bayesians.py in _populate_space function.

Below an example of a trial JSON that causes the error (you can see that some values are NaN) :
{"trial_id": "5e9e66472f6f827a8a4b5b8286adb365", "hyperparameters": {"space": [{"class_name": "Boolean", "config": {"name": "structured_data_block_1/normalize", "default": false, "conditions": []}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/num_layers", "default": 2, "conditions": [], "values": [1, 2, 3], "ordered": true}}, {"class_name": "Boolean", "config": {"name": "structured_data_block_1/dense_block_1/use_batchnorm", "default": false, "conditions": []}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/dropout", "default": 0, "conditions": [], "values": [0.0, 0.25, 0.5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/units_0", "default": 32, "conditions": [], "values": [16, 32, 64, 128, 256, 512, 1024], "ordered": true}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/units_1", "default": 32, "conditions": [], "values": [16, 32, 64, 128, 256, 512, 1024], "ordered": true}}, {"class_name": "Choice", "config": {"name": "regression_head_1/dropout", "default": 0, "conditions": [], "values": [0.0, 0.25, 0.5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "sgd", "adam_weight_decay"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.1, 0.01, 0.001, 0.0001, 2e-05, 1e-05], "ordered": true}}, {"class_name": "Choice", "config": {"name": "structured_data_block_1/dense_block_1/units_2", "default": 32, "conditions": [], "values": [16, 32, 64, 128, 256, 512, 1024], "ordered": true}}], "values": {"structured_data_block_1/normalize": false, "structured_data_block_1/dense_block_1/num_layers": 3, "structured_data_block_1/dense_block_1/use_batchnorm": false, "structured_data_block_1/dense_block_1/dropout": 0.5, "structured_data_block_1/dense_block_1/units_0": 256, "structured_data_block_1/dense_block_1/units_1": 64, "regression_head_1/dropout": 0.25, "optimizer": "sgd", "learning_rate": 0.1, "structured_data_block_1/dense_block_1/units_2": 64}}, "metrics": {"metrics": {"loss": {"direction": "min", "observations": [{"value": [NaN], "step": 0}]}, "mean_squared_error": {"direction": "min", "observations": [{"value": [NaN], "step": 0}]}, "val_loss": {"direction": "min", "observations": [{"value": [NaN], "step": 0}]}, "val_mean_squared_error": {"direction": "min", "observations": [{"value": [NaN], "step": 0}]}}}, "score": NaN, "best_step": null, "status": "COMPLETED"}

**Comment by haifeng-jin** [comment]
I think I understand the bug. It is caused by the NaN value in validation loss which is the metric for evaluation.
We will need to handle it in Keras Tuner.

**Comment by aelgharabawy** [comment]
Hi, I am experiencing the same issue when the val_loss is NaN. I'm using BayesianOptimization as a tuner.

**Comment by aelgharabawy** [comment]
> I have the same issue.
> It happens when the score of the trial is NaN in my case.
> 
> We need to repoen the issue.
> 
> A workaround would be to remove the trial that has a NaN score.

Can you let me know how to do that? (removing a trial for which the val_loss is NaN)

**Comment by aelgharabawy** [comment]
> I have the same issue.
> It happens when the score of the trial is NaN in my case.
> 
> We need to repoen the issue.
> 
> A workaround would be to remove the trial that has a NaN score.

@q-55555 Can you let me know how to do that? (removing a trial for which the val_loss is NaN)

**Comment by koh-joshua** [comment]
I have same issue for latest AutoKeras release using AutoModel for image regresison, with 'bayesian' tuner.

**Comment by haifeng-jin** [comment]
https://github.com/keras-team/keras-tuner/issues/477#issuecomment-786920437
The TerminateonNan callback may be a temporary soluiton.
