### ISSUE TITLE
AutoModel Input 

### ISSUE THREAD

**Issue by CharlesDove** [keras-team/autokeras#1180]
### Bug Description
Good afternoon! I'm currently encountering a bug when initializing the AutoModel system while using an ak.Input() tensor input. It gives the following error. Using any other input, such as ImageInput, works correctly. Any thoughts on what might be causing this?
Thanks!
Charles 

```
Traceback (most recent call last):
  File "learn_distance.py", line 39, in <module>
    reg = ak.AutoModel(inputs=ak.Input(),outputs=ak.ClassificationHead(),max_trials=500,tuner='greedy',overwrite=False)
  File "/home/cadove/.conda/envs/autok2/lib/python3.6/site-packages/autokeras/auto_model.py", line 115, in __init__
    graph = self._build_graph()
  File "/home/cadove/.conda/envs/autok2/lib/python3.6/site-packages/autokeras/auto_model.py", line 185, in _build_graph
    graph = self._assemble()
  File "/home/cadove/.conda/envs/autok2/lib/python3.6/site-packages/autokeras/auto_model.py", line 173, in _assemble
    output_node = middle_nodes[0]
IndexError: list index out of range
```

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.6
 - autokeras: 1.02
 - keras-tuner: 1.0.1
 - scikit-learn: 0.21.2
 - numpy: 1.18.1
 - pandas: 0.25.3
 - tensorflow: 2.1.0

**Comment by haifeng-jin** [comment]
Thank you for the bug report. I think this is fixed in our latest release 1.0.3. You may have a try.

**Comment by spamz23** [comment]
This bug still exists:
`clf = ak.AutoModel(ak.Input(),ak.ClassificationHead(num_classes=2))`
ouputs:
```
/usr/local/lib/python3.6/dist-packages/autokeras/auto_model.py in _assemble(self)
    203             output_node = blocks.Merge()(middle_nodes)
    204         else:
--> 205             output_node = middle_nodes[0]
    206 
    207         outputs = nest.flatten(

IndexError: list index out of range
```

OS type and version: Google colab
Python: 3.6
autokeras: 1.0.7
keras-tuner: 1.0.2rc1
scikit-learn: 0.22.2.post1
numpy: 1.18.5
pandas: 1.0.5
tensorflow: 2.3.0

**Comment by haifeng-jin** [comment]
Sorry about this bug. The main problem is that currently `ak.Input()` is not very well supported. We will try to get to this. Not sure how many people is using this input node.
