### ISSUE TITLE
How use multiple gpu?

### ISSUE THREAD

**Issue by FontTian** [keras-team/autokeras#1238]
### Feature Description
I want to use a single machine with multiple gpu for training, but it seems to have no actual effect### Code Example

```python
with strategy.scope():
```

### Reason
Speed up the calculation of toxins

**Comment by haifeng-jin** [comment]
I think this is supported in Keras-Tuner's Tuner class. AutoKeras supports all args in Tuner class.
You can pass `distribution_strategy` to any model you use in AutoKeras.
The details you can find on this page: https://keras-team.github.io/keras-tuner/documentation/tuners/

**Comment by FontTian** [comment]
emmm,I find it

>distribution_strategy: Optional. A TensorFlow tf.distribute DistributionStrategy instance. If specified, each trial will run under this scope. For example, tf.distribute.MirroredStrategy(['/gpu:0, /'gpu:1]) will run each trial on two GPUs. Currently only single-worker strategies are supported.

and I ran the following code, but an error appeared.

```python

strategy = tf.distribute.MirroredStrategy(['/gpu:0', '/gpu:1'])
# tuner.Tuner(distribution_strategy=strategy)
import autokeras as ak
clf = ak.ImageClassifier(
    overwrite=True,
    max_trials=1,distribution_strategy=strategy)

...
RuntimeError: Too many failed attempts to build model.
```

**Comment by haifeng-jin** [comment]
We didn't fully test this feature with AutoKeras yet. You may try pass one more arg `tuner='random'`. If the error still exists, you may try a basic example with KerasTuner to see if it is a KerasTuner issue. Thanks.

**Comment by AnSmithD** [comment]
Hello, 
got the same issue. I am specifying 4 GPUs (out of 8) to train the current model in a distributed fashion, using `tf.distribute.MirroredStrategy( )` since `tf.keras.utils.multi_gpu_model( )` is deprecated and removed since april 2020.

When doing:

```
def make_model(ckpt_path, max_try = 1):
    
    callbacks = [
    keras.callbacks.ModelCheckpoint(
        filepath=ckpt_path + '/bestMod.hdf5', verbose = 1, monitor="val_accuracy",
                           mode='max', save_best_only = True), 
    keras.callbacks.EarlyStopping(monitor='val_loss', patience=3,  mode='auto')]
    
    
    AutoClassifier = ak.ImageClassifier(directory= "fruits/", 
                   project_name = "fruits_AutoKeras",
                   max_trials = max_try, 
                   metrics = ['accuracy', 'top_k_categorical_accuracy'], 
                   seed = 1245,
                   overwrite = True)     
    
    model = AutoClassifier.fit(
        data_train,
        callbacks=callbacks,
        validation_data=vali_data,
        verbose=2)
    
    return model


def run_search(ckpt_path, max_try = 1):

    strat = tf.distribute.MirroredStrategy()
    
    with strat.scope():
        model = make_model(ckpt_path, max_try)

    return model


run_search(checkpoint, max_try = 3)

```
only one single GPU is doing all the computations, the other three remain idle. When following @FontTian and inserting distribution_strategy=strat into the initialisation of the image classifier, the same Error `RuntimeError: Too many failed attempts to build model.` occurs. Same happens when adding `tuner='random'` to ak.ImageClassifier.

As suggested by @haifeng-jin, I ran a basic KerasTuner example on 4 GPUs and it worked just fine. Furthermore, in https://github.com/keras-team/autokeras/issues/440#issuecomment-592160313 I read that the clear_session() before every run might wipe out the gpu configuration. I also removed this line from the code but nothing changed with respect to the errors/problems above.

Any help is highly appreciated! Thanks in advance

**Comment by haifeng-jin** [comment]
@AnSmithD Thank you for your report. I believe this is a very important bug we need to track down. Would you like to setup a call with us to talk about it? I believe this would be the fastest way to solve it. Please reach me on Slack if you would like to do so. Thank you!

**Comment by ywtaccelerator** [comment]
Hi, is there any update on this topic? Is there currently a workaround to make use of multiple GPUs?

**Comment by haifeng-jin** [comment]
@ywtaccelerator  I am working on another issue related to the tuner right now. Will get to this one right afterwards. Thanks

**Comment by ywtaccelerator** [comment]
@haifeng-jin Thank you! Looking forward to the solving of this issue, I really appreciate your work in AutoKeras.

**Comment by haifeng-jin** [comment]
@FontTian @ywtaccelerator @AnSmithD This bug is fixed in master branch. Please refer to #1285 for fixing details. Thanks.

**Comment by ywtaccelerator** [comment]
@haifeng-jin Thank you very much for your effort and fixing it quickly, but unfortunately it still does not work for me. I have installed AutoKeras from the master branch and ak.__version__ shows its version is 1.0.7, but neither running the Simple Example [here](https://autokeras.com/tutorial/image_classification/) directly, nor trying the ways mentioned above in this page, could make use of multiple GPUs...

Could you double check if it functions well, or briefly describe how to make it work? Thanks!

**Comment by AnSmithD** [comment]
@ywtaccelerator Have you tried uninstalling autokeras and keras-tuner first? And then reinstalling keras-tuner directly via `pip3 install git+https://github.com/keras-team/keras-tuner.git` and **only afterwards** installing autokeras from the master branch?

@haifeng-jin 's fix is working for me (after above described procedure) but unfortunately, it does not seem to result in any performance gains in terms of computing time ...

**Comment by haifeng-jin** [comment]
The solution is also added to the FAQ here:
http://127.0.0.1:8000/tutorial/faq/#how-to-use-multiple-gpus

**Comment by Gorbov** [comment]
@haifeng-jin may I ask you to help with multi GPU?
In order not to create a new topic...

I get an error:
```
Epoch 1/1000
2021-07-27 16:15:38.726497: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-27 16:15:39.515468: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
44/44 [==============================] - ETA: 0s - loss: 0.9194 - accuracy: 0.59802021-07-27 16:15:44.049919: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:695] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_1"
op: "TensorSliceDataset"
input: "Placeholder/_0"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_DOUBLE
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 6558
        }
      }
    }
  }
}
```

For fix this — I need to set:
https://www.tensorflow.org/api_docs/python/tf/data/experimental/AutoShardPolicy

```python
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
```

And how to put this option to StructuredDataClassifier?
```python
model = ak.StructuredDataClassifier(max_trials=params['max_trials'],
				project_name=model_name+ext_type,
				directory='data/models_saved_data/',
				distribution_strategy=tf.distribute.MirroredStrategy()
				)
model.fit(x_train, y_train,
      epochs=params['epochs'],
      batch_size=32,
      )
```

**Comment by BoraYang** [comment]
> @haifeng-jin may I ask you to help with multi GPU?
> In order not to create a new topic...
> 
> I get an error:
> 
> ```
> Epoch 1/1000
> 2021-07-27 16:15:38.726497: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
> 2021-07-27 16:15:39.515468: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
> 44/44 [==============================] - ETA: 0s - loss: 0.9194 - accuracy: 0.59802021-07-27 16:15:44.049919: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:695] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_1"
> op: "TensorSliceDataset"
> input: "Placeholder/_0"
> attr {
>   key: "Toutput_types"
>   value {
>     list {
>       type: DT_DOUBLE
>     }
>   }
> }
> attr {
>   key: "output_shapes"
>   value {
>     list {
>       shape {
>         dim {
>           size: 6558
>         }
>       }
>     }
>   }
> }
> ```
> 
> For fix this — I need to set:
> https://www.tensorflow.org/api_docs/python/tf/data/experimental/AutoShardPolicy
> 
> ```python
> options = tf.data.Options()
> options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
> ```
> 
> And how to put this option to StructuredDataClassifier?
> 
> ```python
> model = ak.StructuredDataClassifier(max_trials=params['max_trials'],
> 				project_name=model_name+ext_type,
> 				directory='data/models_saved_data/',
> 				distribution_strategy=tf.distribute.MirroredStrategy()
> 				)
> model.fit(x_train, y_train,
>       epochs=params['epochs'],
>       batch_size=32,
>       )
> ```

@haifeng-jin Hello, are there any updates regarding this issue?
I've been encountered the same issue above but cannot find any solutions to resolve it.
In addition, the first epoch takes more than three times the execution time of the other epochs.
(Using TF 2.5 - This was not the case when using TF 2.2.)

```
`2021-08-31 13:33:36.871453: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:695] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
op: "TensorSliceDataset"
input: "Placeholder/_0"
input: "Placeholder/_1"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_DOUBLE
      type: DT_INT64
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 400
        }
        dim {
          size: 400
        }
        dim {
          size: 3
        }
      }
      shape {
      }
    }
  }
}

Epoch 1/150
41/41 [==============================] - ETA: 0s - loss: 2.7657 - accuracy: 0.76482021-08-31 13:34:17.103770: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:695] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
op: "TensorSliceDataset"
input: "Placeholder/_0"
input: "Placeholder/_1"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_DOUBLE
      type: DT_INT64
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 400
        }
        dim {
          size: 400
        }
        dim {
          size: 3
        }
      }
      shape {
      }
    }
  }
}

41/41 [==============================] - **42s 511ms/step** - loss: 2.7657 - accuracy: 0.7648 - val_loss: 3.9927 - val_accuracy: 0.5000`

Epoch 2/150
41/41 [==============================] - 13s 308ms/step - loss: 2.1608 - accuracy: 0.4713 - val_loss: 4.2967 - val_accuracy: 0.5000

Epoch 3/150
41/41 [==============================] - 12s 298ms/step - loss: 1.9844 - accuracy: 0.4695 - val_loss: 0.9744 - val_accuracy: 0.5000
```

**Comment by giuliotosato** [comment]
this will solve the problem:

`test_dataset = tf.data.Dataset.from_tensor_slices((test_data, test_labels))
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
test_dataset = test_dataset.with_options(options)

strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    m=[tfa.metrics.F1Score(num_classes=20, average='macro',threshold=0.5),tf.keras.metrics.Precision(),tf.keras.metrics.Recall()]
clf = ak.ImageClassifier(
                    directory='/home/u956278/research_workshop/model_final',
                    max_trials=5,
                    objective=kerastuner.Objective('val_f1_score', direction='max'),
                    distribution_strategy=strategy,
                    metrics=m)
clf.fit(train_dataset, 
    	#epochs=130, callbacks=[tf.keras.callbacks.EarlyStopping(monitor="val_f1_score",patience=7,restore_best_weights=True)], 
        epochs=100, 
        #callbacks=[tf.keras.callbacks.EarlyStopping(patience=7,restore_best_weights=True)], 
    	batch_size=512, 
    	validation_data=test_dataset,
        verbose=2,
        class_weight=class_weights,
        shuffle=False,
        workers=64,
        max_queue_size=32
       )`
